# Generated by Django 3.0.7 on 2020-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_images',
            field=models.ImageField(default='default.png', upload_to='media'),
        ),
    ]
